version: 2

models:
  - name: silver_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: customer_status
        tests:
          - accepted_values:
              values: ['ACTIVE', 'DORMANT', 'SUSPENDED']

  - name: silver_accounts
    columns:
      - name: account_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_customers')
              field: customer_id

  - name: silver_fx_rates
    columns:
      - name: rate_date
        tests:
          - not_null
      - name: exchange_rate
        tests:
          - not_null

  - name: silver_transactions
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_accounts')
              field: account_id
      - name: status
        tests:
          - accepted_values:
              values: ['PENDING', 'SETTLED', 'FAILED', 'REVERSED']
      - name: amount_usd
        tests:
          - not_null

  - name: silver_transactions_rejected
    columns:
      - name: rejection_reason
        tests:
          - not_null
